/*
SQLyog v10.2 
MySQL - 5.5.43 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `dictionary_table` (
	`id` varchar (192),
	`table_name` varchar (768),
	`table_comment` varchar (192),
	`table_description` varchar (768),
	`sequence_id` varchar (768),
	`table_remark` varchar (3072),
	`create_time` datetime ,
	`update_time` datetime ,
	`create_staff_id` varchar (192),
	`update_staff_id` varchar (192),
	`delete_state` varchar (6)
); 
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_0','tb_0','tbcomm_0','tbdesc_0','tbseq_0','tbremark_0','2018-01-15 23:40:05',NULL,'0','0','1');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_1','tb_1','tbcomm_1','tbdesc_1','tbseq_1','tbremark_1','2018-01-15 23:40:05',NULL,'0','0','1');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_2','tb_2','tbcomm_2','tbdesc_2','tbseq_2','tbremark_2','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_3','tb_3','tbcomm_3','tbdesc_3','tbseq_3','tbremark_3','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_4','tb_4','tbcomm_4','tbdesc_4','tbseq_4','tbremark_4','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_5','tb_5','tbcomm_5','tbdesc_5','tbseq_5','tbremark_5','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_6','tb_6','tbcomm_6','tbdesc_6','tbseq_6','tbremark_6','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_7','tb_7','tbcomm_7','tbdesc_7','tbseq_7','tbremark_7','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_8','tb_8','tbcomm_8','tbdesc_8','tbseq_8','tbremark_8','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_9','tb_9','tbcomm_9','tbdesc_9','tbseq_9','tbremark_9','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_10','tb_10','tbcomm_10','tbdesc_10','tbseq_10','tbremark_10','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_11','tb_11','tbcomm_11','tbdesc_11','tbseq_11','tbremark_11','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_12','tb_12','tbcomm_12','tbdesc_12','tbseq_12','tbremark_12','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_13','tb_13','tbcomm_13','tbdesc_13','tbseq_13','tbremark_13','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_14','tb_14','tbcomm_14','tbdesc_14','tbseq_14','tbremark_14','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_15','tb_15','tbcomm_15','tbdesc_15','tbseq_15','tbremark_15','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_16','tb_16','tbcomm_16','tbdesc_16','tbseq_16','tbremark_16','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_17','tb_17','tbcomm_17','tbdesc_17','tbseq_17','tbremark_17','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_18','tb_18','tbcomm_18','tbdesc_18','tbseq_18','tbremark_18','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_19','tb_19','tbcomm_19','tbdesc_19','tbseq_19','tbremark_19','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_20','tb_20','tbcomm_20','tbdesc_20','tbseq_20','tbremark_20','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_21','tb_21','tbcomm_21','tbdesc_21','tbseq_21','tbremark_21','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_22','tb_22','tbcomm_22','tbdesc_22','tbseq_22','tbremark_22','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_23','tb_23','tbcomm_23','tbdesc_23','tbseq_23','tbremark_23','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_24','tb_24','tbcomm_24','tbdesc_24','tbseq_24','tbremark_24','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_25','tb_25','tbcomm_25','tbdesc_25','tbseq_25','tbremark_25','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_26','tb_26','tbcomm_26','tbdesc_26','tbseq_26','tbremark_26','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_27','tb_27','tbcomm_27','tbdesc_27','tbseq_27','tbremark_27','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_28','tb_28','tbcomm_28','tbdesc_28','tbseq_28','tbremark_28','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_29','tb_29','tbcomm_29','tbdesc_29','tbseq_29','tbremark_29','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_30','tb_30','tbcomm_30','tbdesc_30','tbseq_30','tbremark_30','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_31','tb_31','tbcomm_31','tbdesc_31','tbseq_31','tbremark_31','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_32','tb_32','tbcomm_32','tbdesc_32','tbseq_32','tbremark_32','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_33','tb_33','tbcomm_33','tbdesc_33','tbseq_33','tbremark_33','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_34','tb_34','tbcomm_34','tbdesc_34','tbseq_34','tbremark_34','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_35','tb_35','tbcomm_35','tbdesc_35','tbseq_35','tbremark_35','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_36','tb_36','tbcomm_36','tbdesc_36','tbseq_36','tbremark_36','2018-01-15 23:40:05',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_37','tb_37','tbcomm_37','tbdesc_37','tbseq_37','tbremark_37','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_38','tb_38','tbcomm_38','tbdesc_38','tbseq_38','tbremark_38','2018-01-15 23:40:06',NULL,'0','0','1');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_39','tb_39','tbcomm_for_update','tbdesc_39','tbseq_39','tbremark_39','2018-01-15 23:40:06','2018-01-15 23:51:17','0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_40','tb_40','tbcomm_40','tbdesc_40','tbseq_40','tbremark_40','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_41','tb_41','tbcomm_41','tbdesc_41','tbseq_41','tbremark_41','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_42','tb_42','tbcomm_42','tbdesc_42','tbseq_42','tbremark_42','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_43','tb_43','tbcomm_43','tbdesc_43','tbseq_43','tbremark_43','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_44','tb_44','tbcomm_44','tbdesc_44','tbseq_44','tbremark_44','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_45','tb_45','tbcomm_45','tbdesc_45','tbseq_45','tbremark_45','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_46','tb_46','tbcomm_46','tbdesc_46','tbseq_46','tbremark_46','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_47','tb_47','tbcomm_47','tbdesc_47','tbseq_47','tbremark_47','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_48','tb_48','tbcomm_48','tbdesc_48','tbseq_48','tbremark_48','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_49','tb_49','tbcomm_49','tbdesc_49','tbseq_49','tbremark_49','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_50','tb_50','tbcomm_50','tbdesc_50','tbseq_50','tbremark_50','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_51','tb_51','tbcomm_51','tbdesc_51','tbseq_51','tbremark_51','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_52','tb_52','tbcomm_52','tbdesc_52','tbseq_52','tbremark_52','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_53','tb_53','tbcomm_53','tbdesc_53','tbseq_53','tbremark_53','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_54','tb_54','tbcomm_54','tbdesc_54','tbseq_54','tbremark_54','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_55','tb_55','tbcomm_55','tbdesc_55','tbseq_55','tbremark_55','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_56','tb_56','tbcomm_56','tbdesc_56','tbseq_56','tbremark_56','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_57','tb_57','tbcomm_57','tbdesc_57','tbseq_57','tbremark_57','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_58','tb_58','tbcomm_58','tbdesc_58','tbseq_58','tbremark_58','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_59','tb_59','tbcomm_59','tbdesc_59','tbseq_59','tbremark_59','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_60','tb_60','tbcomm_60','tbdesc_60','tbseq_60','tbremark_60','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_61','tb_61','tbcomm_61','tbdesc_61','tbseq_61','tbremark_61','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_62','tb_62','tbcomm_62','tbdesc_62','tbseq_62','tbremark_62','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_63','tb_63','tbcomm_63','tbdesc_63','tbseq_63','tbremark_63','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_64','tb_64','tbcomm_64','tbdesc_64','tbseq_64','tbremark_64','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_65','tb_65','tbcomm_65','tbdesc_65','tbseq_65','tbremark_65','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_66','tb_66','tbcomm_66','tbdesc_66','tbseq_66','tbremark_66','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_67','tb_67','tbcomm_67','tbdesc_67','tbseq_67','tbremark_67','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_68','tb_68','tbcomm_68','tbdesc_68','tbseq_68','tbremark_68','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_69','tb_69','tbcomm_69','tbdesc_69','tbseq_69','tbremark_69','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_70','tb_70','tbcomm_70','tbdesc_70','tbseq_70','tbremark_70','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_71','tb_71','tbcomm_71','tbdesc_71','tbseq_71','tbremark_71','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_72','tb_72','tbcomm_72','tbdesc_72','tbseq_72','tbremark_72','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_73','tb_73','tbcomm_73','tbdesc_73','tbseq_73','tbremark_73','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_74','tb_74','tbcomm_74','tbdesc_74','tbseq_74','tbremark_74','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_75','tb_75','tbcomm_75','tbdesc_75','tbseq_75','tbremark_75','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_76','tb_76','tbcomm_76','tbdesc_76','tbseq_76','tbremark_76','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_77','tb_77','tbcomm_77','tbdesc_77','tbseq_77','tbremark_77','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_78','tb_78','tbcomm_78','tbdesc_78','tbseq_78','tbremark_78','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_79','tb_79','tbcomm_79','tbdesc_79','tbseq_79','tbremark_79','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_80','tb_80','tbcomm_80','tbdesc_80','tbseq_80','tbremark_80','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_81','tb_81','tbcomm_81','tbdesc_81','tbseq_81','tbremark_81','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_82','tb_82','tbcomm_82','tbdesc_82','tbseq_82','tbremark_82','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_83','tb_83','tbcomm_83','tbdesc_83','tbseq_83','tbremark_83','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_84','tb_84','tbcomm_84','tbdesc_84','tbseq_84','tbremark_84','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_85','tb_85','tbcomm_85','tbdesc_85','tbseq_85','tbremark_85','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_86','tb_86','tbcomm_86','tbdesc_86','tbseq_86','tbremark_86','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_87','tb_87','tbcomm_87','tbdesc_87','tbseq_87','tbremark_87','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_88','tb_88','tbcomm_88','tbdesc_88','tbseq_88','tbremark_88','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_89','tb_89','tbcomm_89','tbdesc_89','tbseq_89','tbremark_89','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_90','tb_90','tbcomm_90','tbdesc_90','tbseq_90','tbremark_90','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_91','tb_91','tbcomm_91','tbdesc_91','tbseq_91','tbremark_91','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_92','tb_92','tbcomm_92','tbdesc_92','tbseq_92','tbremark_92','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_93','tb_93','tbcomm_93','tbdesc_93','tbseq_93','tbremark_93','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_94','tb_94','tbcomm_94','tbdesc_94','tbseq_94','tbremark_94','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_95','tb_95','tbcomm_95','tbdesc_95','tbseq_95','tbremark_95','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('dictb_96','tb_96','tbcomm_96','tbdesc_96','tbseq_96','tbremark_96','2018-01-15 23:40:06',NULL,'0','0','0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('1521273576159','a','aa','aaa',NULL,'aaaa','2018-03-17 15:59:36',NULL,NULL,NULL,'0');
insert into `dictionary_table` (`id`, `table_name`, `table_comment`, `table_description`, `sequence_id`, `table_remark`, `create_time`, `update_time`, `create_staff_id`, `update_staff_id`, `delete_state`) values('1521384426897','hello_tb','fsf','fsfff',NULL,'fsfsff','2018-03-18 22:47:06',NULL,NULL,NULL,'0');
